config:
  subprojects: ./testset
  env:
    - env_A=0
    - env_B=1
  junit:
    allowEmptyResults: true
    keepLongStdio: true
    testResults: '*.xml'

stages:
 - job1
 - job2

stage:
  job1:
    node: master
    script:
     - sh: echo "job1 env_A=${env_A} env_C=${env_C} env_D=${env_D}"
     - sh: ls -al
     - sh: pwd
     - sh: sh ./mkresult junit1.xml
     - echo: "echo job1"
    env:
     - env_C="C"
     - env_D="D"
    result: '*.xml'

  job2:
    node: master
    script:
     - sh: echo "job2"
     - sh: ls -al
     - sh: pwd
     - sh: sh ./mkresult junit2.xml
     - sh: echo "job2 env_C=${env_C} env_D=${env_D}"
    result: '*.xml'

  para_job1:
    parallel:
     - job1
     - job2

  para_job2:
    parallel:
     - para_job1
     - para_job1
