config:
  subprojects: ./testset
  env:
    - env_A=0
    - env_B=1

stages:
 - job1

stage:
  job1:
    node: master
    script:
     - sh: echo "job1"
  job2:
    node: master
    script:
     - sh: echo "job2"

