config:
  subprojects: ./testset
  env:
    - env_A=0
    - env_B=1

stages:
 - para_job1
 - job1
 - job2
 - para_job2

stage:
  job1:
    node: master
    script:
     - sh: echo "job1"
     - sh: ls -al
     - sh: pwd
     - echo: "echo job1"
  job2:
    node: master
    script:
     - sh: echo "job2"
     - sh: ls -al
     - sh: pwd
     - echo: "echo job1"
  para_job1:
    parallel:
     - job1
     - job2
  para_job2:
    parallel:
     - para_job1
     - para_job1
