config:
  env:
    - env_A=10
    - env_B=11

stages:
 - sample_job1
 - sample_job2

stage:
  sample_job1:
    node: master
    script:
     - sh: echo "sample_job1 env_A=${env_A} env_C=${env_C} env_D=${env_D}"
     - sh: pwd
     - sh: sh ./mkresult result/sample_job1.xml
     - sh: ls ${jobpath}
     - sh: ls -R
    env:
     - env_C="C"
     - env_D="D"
    result: 'result/*.xml'

  sample_job2:
    node: master
    script:
     - sh: echo "sample_job2 env_C=${env_C} env_D=${env_D}"
     - sh: pwd
     - sh: sh ./mkresult result/sample_job2.xml
     - sh: ls -R
    result: 'result/*.xml'
